version: '3.8'
services:
  app:
    build: .
    ports:
      - '3333:3000' # ローカルホストのポート3333をコンテナのポート3000にマッピング
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev

  storybook:
    build: .
    ports:
      - '6666:6006' # ローカルホストのポート6666をコンテナのポート6006にマッピング
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn storybook
