import Head from 'next/head'
import ChartBar from '@/components/Chart/ChartBar'
import Typography from '@mui/material/Typography'
import styles from '../styles/Home.module.css'

const App = () => {
  return (
    <>
      {/* page meta */}
      <Head>
        <title>Ag-Next-Mui</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      {/* content */}
      <main className={styles.main}>
        {/* <div className={styles.grid}> */}
        <h2 className={styles.head_2} style={{ marginTop: 16 }}>
          Chart
        </h2>
        <ChartBar />
      </main>
    </>
  )
}

export default App
